# Generated by Django 4.2.16 on 2024-12-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
