# Generated by Django 4.2.16 on 2024-12-19 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0003_alter_review_reviewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='user',
        ),
    ]
