# Generated by Django 4.2.16 on 2024-12-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0004_remove_flower_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
