# Generated by Django 4.2.16 on 2024-12-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0005_alter_flower_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='FlowerMalik',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
