# Generated by Django 4.2.16 on 2024-12-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_order_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobile_no',
            field=models.CharField(max_length=11),
        ),
    ]
